//
// Created by ShawnGao on 2022/7/31.
//

#ifndef JUDGE_CORE_EXIT_STATUS_CODE_H
#define JUDGE_CORE_EXIT_STATUS_CODE_H

enum {
    WRONG_CONFIG_VALUE = -1,
    INVALID_OPTION = -2
};

#endif //JUDGE_CORE_EXIT_STATUS_CODE_H
